pathrouter:
  image: foodpedia/pathrouter
  ports:
    - "80:80"
  links:
    - endpoint
    - pubby
    - home
    - foodontologycontentnegotiator

home:
  build: ./foodpedia-home

pubby:
  image: foodpedia/pubby
  links:
    - endpoint
  command: http://localhost http://endpoint:8890/sparql

endpoint:
  image: foodpedia/virtuoso_ontowiki
  volumes:
    - ./upload:/upload
  ports:
    - "8008:80"

foodontologycontentnegotiator:
  build: foodpedia-servlet
